[project]
name = "nanodjango-examples"
version = "0.0.0-dev0"
description = "Examples on how to make the most of nanodjango."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "nanodjango>=0.11.2",
]

[dependency-groups]
dev = []
